### ISSUE TITLE
About info available on left

### ISSUE THREAD

**Issue by mikelmaron** [mikelmaron/congress-maps#2]

**Comment by DylanMoriarty** [comment]
I thought it might be nice to have the 'about' basically just be the welcome content. Do you know what sort of text you'd want to throw in there?

<img width="1183" alt="screenshot 2017-02-09 09 01 10" src="https://cloud.githubusercontent.com/assets/9341928/22786388/50607430-eea6-11e6-9070-2149d67eef57.png">
